import {
  siCss,
  siGit,
  siGithub,
  siHtml5,
  siJavascript,
  siJetpackcompose,
  siKotlin,
  siNextdotjs,
  siNodedotjs,
  siPostgresql,
  siReact,
  siShadcnui,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siVercel,
  siVite,
  siWhatsapp,
  siZod,
  siChartdotjs,
  type SimpleIcon,
} from "simple-icons";

/** Explicit map keeps the bundle to the icons we actually use. Add new entries here. */
export const TECH_ICONS: Record<string, SimpleIcon> = {
  javascript: siJavascript,
  typescript: siTypescript,
  kotlin: siKotlin,
  react: siReact,
  nextdotjs: siNextdotjs,
  vite: siVite,
  jetpackcompose: siJetpackcompose,
  tailwindcss: siTailwindcss,
  html5: siHtml5,
  css: siCss,
  supabase: siSupabase,
  postgresql: siPostgresql,
  vercel: siVercel,
  git: siGit,
  github: siGithub,
  whatsapp: siWhatsapp,
  chartdotjs: siChartdotjs,
  zod: siZod,
  nodedotjs: siNodedotjs,
  shadcnui: siShadcnui,
};
